# Typical File for extension: vscode-graphql & CodeGen!
projects:
  default:
    schema: https://sayhello.how/graphql
    documents: './src/lib/graphql/*.gql'
    extensions:
      codegen:
        generates:
          ./src/lib/graphql/_kitql/graphqlTypes.ts:
            plugins:
              - typescript
              - typescript-operations
              - typed-document-node
              - typescript-document-nodes

          ./src/lib/graphql/_kitql/graphqlStores.ts:
            plugins:
              - '@kitql/graphql-codegen'
            config:
              importBaseTypesFrom: $lib/graphql/_kitql/graphqlTypes
              operationPrefix: 'KQL_'
        config:
          useTypeImports: true
          namingConvention:
            transformUnderscore: true
