query SINGLE_LANG($title: String!) {
  posts(where: { title: $title }) {
    edges {
      node {
        title
        slug
        simpleLanguages {
          slcTheWord
          slcTheSound
        }
      }
    }
  }
}
